"""Create site_id, min_salary_, max_salary, salary_currency, salary_period fields for JobVacancy table

Revision ID: 003
Revises: 002
Create Date: 2024-11-10 06:51:46.367234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_vacancies', sa.Column('site_id', sa.String(), nullable=False))
    op.add_column('job_vacancies', sa.Column('min_salary', sa.Integer(), nullable=False))
    op.add_column('job_vacancies', sa.Column('max_salary', sa.Integer(), nullable=False))
    op.add_column('job_vacancies', sa.Column('salary_currency', sa.String(), nullable=False))
    op.add_column('job_vacancies', sa.Column('salary_period', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'job_vacancies', ['site_id'])
    op.create_unique_constraint(None, 'job_vacancies', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_vacancies', type_='unique')
    op.drop_constraint(None, 'job_vacancies', type_='unique')
    op.drop_column('job_vacancies', 'salary_period')
    op.drop_column('job_vacancies', 'salary_currency')
    op.drop_column('job_vacancies', 'max_salary')
    op.drop_column('job_vacancies', 'min_salary')
    op.drop_column('job_vacancies', 'site_id')
    # ### end Alembic commands ###
