"""Remove id from JobVacancy

Revision ID: 004
Revises: 003
Create Date: 2024-11-10 07:04:17.097015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '004'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_vacancies', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.String(),
               existing_nullable=False,
               autoincrement=False)
    op.drop_constraint('job_vacancies_site_id_key', 'job_vacancies', type_='unique')
    op.drop_column('job_vacancies', 'site_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_vacancies', sa.Column('site_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('job_vacancies_site_id_key', 'job_vacancies', ['site_id'])
    op.alter_column('job_vacancies', 'id',
               existing_type=sa.String(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
