"""Add title column for channel table

Revision ID: 006
Revises: 005
Create Date: 2024-11-12 06:34:50.255037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '006'
down_revision: Union[str, None] = '005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('title', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'channels', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'channels', type_='unique')
    op.drop_column('channels', 'title')
    # ### end Alembic commands ###
