"""Rename Channels table column

Revision ID: 007
Revises: 006
Create Date: 2024-11-12 07:27:25.046016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('post_interval', sa.Integer(), nullable=False))
    op.drop_column('channels', 'post_n_every_hours')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('post_n_every_hours', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('channels', 'post_interval')
    # ### end Alembic commands ###
