"""Create category column for vacancy

Revision ID: 015
Revises: 014
Create Date: 2024-11-14 05:20:26.386818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '015'
down_revision: Union[str, None] = '014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_vacancies', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'job_vacancies', 'job_vacancy_categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_vacancies', type_='foreignkey')
    op.drop_column('job_vacancies', 'category_id')
    # ### end Alembic commands ###
