"""Add name_en field for vacancies category

Revision ID: 023
Revises: 022
Create Date: 2024-11-25 00:59:44.894982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023'
down_revision: Union[str, None] = '022'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_vacancy_categories', sa.Column('name_en', sa.String(), nullable=True))
    op.drop_constraint('job_vacancy_categories_name_key', 'job_vacancy_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('job_vacancy_categories_name_key', 'job_vacancy_categories', ['name'])
    op.drop_column('job_vacancy_categories', 'name_en')
    # ### end Alembic commands ###
