"""Rename users_subscripitons table to users_category_subscriptions

Revision ID: 024
Revises: 023
Create Date: 2024-11-25 03:06:25.415611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024'
down_revision: Union[str, None] = '023'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_category_subscriptions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['job_vacancy_categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    op.drop_table('user_subscriptions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_subscriptions',
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['job_vacancy_categories.id'], name='user_subscriptions_category_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_subscriptions_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'category_id', name='user_subscriptions_pkey')
    )
    op.drop_table('user_category_subscriptions')
    # ### end Alembic commands ###
