"""Rename keyword field in users table to subscribed_keyword

Revision ID: 031
Revises: 030
Create Date: 2024-11-25 15:38:50.336157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031'
down_revision: Union[str, None] = '030'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscribed_keyword', sa.String(), nullable=True))
    op.drop_column('users', 'keyword')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keyword', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'subscribed_keyword')
    # ### end Alembic commands ###
